[package]
name = "sssp"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
rand = "0.9"

[dev-dependencies]
bench = { path = "../bench" }
criterion = "0.8.1"

[[bench]]
name = "sssp"
harness = false
