[package]
name = "gcd"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dev-dependencies]
bench = { path = "../bench" }
criterion = "0.8.1"

[[bench]]
name = "gcd"
harness = false
